version: '2.1'

services:
  proxy:
    image: unicef/etools-prp-nginx-proxy
    environment:
      - DJANGO_APPLICATION_SERVICE_HOST=django_api
    build:
      context: ./nginx_proxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - django_api
      - polymer

  django_api:
    image: unicef/etools-prp
    env_file:
      - .env
    build:
      context: ./django_api
      dockerfile: ./Dockerfile
      args:
        ENV: dev
        REQUIREMENT_FILE: dev.txt
    volumes:
      - './django_api:/code/'
    command: bash -c "/usr/local/bin/waitforit -host=db -port=5432 && python /code/manage.py makemigrations --merge --noinput && python /code/manage.py migrate && python manage.py collectstatic --noinput && uwsgi --ini /code/django_api/uwsgi.ini"
    depends_on:
      - db

  db:
    image: unicef/etools-prp-db
    env_file:
      - .env
    build:
      context: ./db
      dockerfile: ./Dockerfile
#    volumes:
#      - './postgres_data:/var/lib/postgresql/data'

  redis:
    image: unicef/etools-prp-redis
    build:
      context: ./redis
      dockerfile: ./Dockerfile

  polymer:
    image: unicef/etools-prp-polymer
    build:
      context: ./polymer
      dockerfile: ./Dockerfile-bundle
    volumes:
        - ./polymer/:/code
        - /code/node_modules
        - /code/bower_components
    command: ash -c "node express.js"
